services:
  app:
    build: .
    container_name: url-minifier
    environment:
      PORT: 8085
      REDIS_URL: redis://redis:6379
    ports:
      - "8085:8085"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
