services:
  app:
    build: .
    container_name: url-minifier
    environment:
      PORT: 8085
      DB_URI: ${DB_URI}
    ports:
      - "8085:8085"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

